Repository Roave/psr-container-doctrine, pull requests merged in 2020-02, with the labels that each got.

#1 Updates for Roave takeover of container-interop-doctrine
  .coveralls.yml
  .gitignore
  .travis.yml
  LICENSE
  README.md
  bc-namespace-shim.php
  composer.json
  composer.lock
  example/aura-di.php
  example/full-config.php
  example/laminas-servicemanager.php
  example/minimal-config.php
  example/pimple-interop.php
  phpcs.xml
  phpunit.xml.dist
  psalm.xml.dist
  src/AbstractFactory.php
  src/CacheFactory.php
  src/ConfigurationFactory.php
  src/ConnectionFactory.php
  src/DriverFactory.php
  src/EntityManagerFactory.php
  src/EventManagerFactory.php
  src/Exception/DomainException.php
  src/Exception/ExceptionInterface.php
  src/Exception/InvalidArgumentException.php
  src/Exception/OutOfBoundsException.php
  test/AbstractFactoryTest.php
  test/CacheFactoryTest.php
  test/ConnectionFactoryTest.php
  test/DriverFactoryTest.php
  test/EntityManagerFactoryTest.php
  test/EventManagerFactoryTest.php
  test/TestAsset/StubEventListener.php
  test/TestAsset/StubEventSubscriber.php
  test/TestAsset/StubFactory.php
  test/TestAsset/StubFileDriver.php
Labels: BC BREAK, enhancement

#6 AbstractFactory is now @internal and inheritors are final
  CHANGELOG.md
  README.md
  src/AbstractFactory.php
  src/CacheFactory.php
  src/ConfigurationFactory.php
  src/ConnectionFactory.php
  src/DriverFactory.php
  src/EntityManagerFactory.php
  src/EventManagerFactory.php
Labels: BC BREAK, enhancement

#9 Eliminate issues from static analysis checks
  .travis.yml
  CHANGELOG.md
  psalm.xml.dist
  src/AbstractFactory.php
  src/CacheFactory.php
  src/ConfigurationFactory.php
  src/ConnectionFactory.php
  src/DriverFactory.php
  src/EntityManagerFactory.php
  src/EventManagerFactory.php
  test/AbstractFactoryTest.php
  test/ConnectionFactoryTest.php
  test/DriverFactoryTest.php
  test/EntityManagerFactoryTest.php
  test/EventManagerFactoryTest.php
  test/TestAsset/StubFactory.php
  test/TestAsset/StubFileDriver.php
Labels: BC BREAK, enhancement

#11 Simplify driver class check
  src/DriverFactory.php
Labels: enhancement

#12 Replace Prophecy mocks with PHPUnit mocks enhancement
  psalm.xml.dist
  test/AbstractFactoryTest.php
  test/CacheFactoryTest.php
  test/ConnectionFactoryTest.php
  test/DriverFactoryTest.php
  test/EntityManagerFactoryTest.php
  test/EventManagerFactoryTest.php
Labels: enhancement

#14 Increase test coverage + a few improvements
  .travis.yml
  src/AbstractFactory.php
  src/CacheFactory.php
  src/ConnectionFactory.php
  src/DriverFactory.php
  src/EventManagerFactory.php
  src/Exception/DomainException.php
  src/Exception/InvalidArgumentException.php
  src/Exception/OutOfBoundsException.php
  test/CacheFactoryTest.php
  test/ConnectionFactoryTest.php
  test/EventManagerFactoryTest.php
Labels: BC BREAK, enhancement

#13 Add Roave BackwardCompatibilityCheck to check for BC breaks
  .travis.yml
  Makefile
Labels: enhancement

#18 Make sure `MappingDriverChain` is still instantiated without a default driver if not configured
  src/DriverFactory.php
  test/DriverFactoryTest.php
Labels: bug

#19 Merge release 2.1.1 into master
  src/DriverFactory.php
  test/DriverFactoryTest.php
Labels: bug

#21 Rely on existence of the default_driver key on final merged config
  example/full-config.php
  src/DriverFactory.php
Labels: bug
