Repository Roave/psr-container-doctrine, pull requests merged in 2021-04, with the labels that each got.

#35 Doctrine migrations version 3
  .travis.yml
  README.md
  composer.json
  composer.lock
  example/full-config.php
  phpunit.xml.dist
  src/AbstractFactory.php
  src/CacheFactory.php
  src/ConfigurationFactory.php
  src/ConnectionFactory.php
  src/DriverFactory.php
  src/EntityManagerFactory.php
  src/EventManagerFactory.php
  src/Exception/DomainException.php
  src/Exception/InvalidArgumentException.php
  src/Exception/OutOfBoundsException.php
  src/Migrations/CommandFactory.php
  src/Migrations/ConfigurationLoaderFactory.php
  src/Migrations/DependencyFactoryFactory.php
  src/MigrationsCommandFactory.php
  src/MigrationsConfigurationFactory.php
  test/AbstractFactoryTest.php
  test/CacheFactoryTest.php
  test/ConnectionFactoryTest.php
  test/DriverFactoryTest.php
  test/EntityManagerFactoryTest.php
  test/EventManagerFactoryTest.php
  test/Migrations/CommandFactoryTest.php
  test/Migrations/ConfigurationLoaderFactoryTest.php
  test/Migrations/DependencyFactoryFactoryTest.php
  test/MigrationsCommandFactoryTest.php
  test/MigrationsConfigurationFactoryTest.php
  test/TestAsset/StubEventListener.php
  test/TestAsset/StubEventSubscriber.php
  test/TestAsset/StubFactory.php
  test/TestAsset/StubFileDriver.php
Labels: BC BREAK, WIP, enhancement

#16 Removed the BC shim for old namespace
  bc-namespace-shim.php
  composer.json
Labels: BC BREAK, enhancement

#38 Migrate from Travis CI to GitHub Actions …
  .github/workflows/main.yml
  .travis.yml
  README.md
Labels: enhancement

#41 Added Laminas Automatic-Releases to GH actions
  .github/workflows/coding-standards.yml
  .github/workflows/release-on-milestone-closed-triggering-release-event.yml
  .github/workflows/roave-bc-check.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
  README.md
Labels: enhancement

#43 README.md: fix class reference
  README.md
Labels: bug
