Repository Roave/psr-container-doctrine, pull requests merged in 2023-10, with the labels that each got.

#104 Update CLI documentation to add `bin/doctrine`
  README.md
Labels: documentation

#107 [Feature] Define schema assets filter in configuration
  example/full-config.php
  src/ConfigurationFactory.php
  test/ConfigurationFactoryTest.php
Labels: documentation, enhancement

#110 Add support for `doctrine/cache:v2`
  .github/workflows/test.yml
  composer.json
  composer.lock
  example/composer.json
  example/full-config.php
  psalm.xml.dist
  src/Cache/NullCache.php
  src/Cache/NullCacheItem.php
  src/CacheFactory.php
  src/ConfigurationFactory.php
  test/Cache/NullCacheTest.php
  test/CacheFactoryTest.php
  test/DriverFactoryTest.php
Labels: enhancement, BC BREAK
